version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name aws-final-app --s3-location s3://aws-final-kadai-bucket-0628/artifact.zip --source .

artifacts:
  files:
    - '**/*'